import { NextRequest, NextResponse } from "next/server";
import { CLASSROOM_LANGUAGES, CLASSROOM_REGISTERS, LAUNCH_ERROR_TEXT } from "@converso/contracts";
import {
    noteClassroomExchange,
    recordClassroomSession,
} from "@/lib/actions/simulation.actions";
import { corsHeaders, readLaunchToken } from "@/lib/launch";

/**
 * The language room's own bookkeeping.
 *
 * Two things happen here and nothing else: the room declares which language and
 * register it is in, and it counts an exchange when the teacher answers.
 *
 * Note what is *not* here. The answers themselves are generated by Ollama on the
 * student's own machine and never leave it; the model name is recorded, the
 * sentences are not. That was a deliberate property of the classroom before this
 * integration and staying out of the way of it is the whole job.
 */

export async function POST(req: NextRequest) {
    const token = readLaunchToken(req);
    if (!token.ok) {
        const code = token.error as keyof typeof LAUNCH_ERROR_TEXT;
        return NextResponse.json(
            { error: code, message: LAUNCH_ERROR_TEXT[code] },
            { status: 401, headers: corsHeaders(req) },
        );
    }

    let body: { language?: string; register?: string; event?: string; model?: string };
    try {
        body = await req.json();
    } catch {
        return NextResponse.json(
            { error: "BAD_BODY", message: "Malformed request body." },
            { status: 400, headers: corsHeaders(req) },
        );
    }

    const sessionId = token.claims.sessionId;
    const userId = token.claims.userId;

    try {
        if (body.event === "exchange") {
            await noteClassroomExchange({
                sessionId,
                userId,
                model: typeof body.model === "string" ? body.model.slice(0, 120) : null,
            });
            return new NextResponse(null, { status: 204, headers: corsHeaders(req) });
        }

        // Anything else is the room announcing itself. Validate against the
        // contract list rather than the check constraint — a 400 with a reason
        // beats a Postgres 23514 with a column name.
        const language = CLASSROOM_LANGUAGES.includes(body.language as string)
            ? (body.language as string)
            : null;

        if (!language) {
            return NextResponse.json(
                { error: "BAD_BODY", message: `language must be one of ${CLASSROOM_LANGUAGES.join(", ")}` },
                { status: 400, headers: corsHeaders(req) },
            );
        }

        const register = CLASSROOM_REGISTERS.includes(body.register as string)
            ? (body.register as "formal" | "casual")
            : "formal";

        await recordClassroomSession({ sessionId, userId, language, register });

        return NextResponse.json({ ok: true }, { headers: corsHeaders(req) });
    } catch (err) {
        console.error("[classroom/session]", err);
        return NextResponse.json(
            { error: "UNAVAILABLE", message: LAUNCH_ERROR_TEXT.UNAVAILABLE },
            { status: 500, headers: corsHeaders(req) },
        );
    }
}

export async function OPTIONS(req: NextRequest) {
    return new NextResponse(null, { status: 204, headers: corsHeaders(req) });
}
