"use client";

/**
 * The launch handshake, for a room that is also a Next app.
 *
 * A classroom can be opened two ways, and this file is the difference between
 * them.
 *
 *   standalone   `npm run dev`, no query string. Nothing here runs. The room
 *                behaves exactly as it did before any of this existed: pick a
 *                language, ask the teacher, nothing is recorded anywhere.
 *
 *   launched     opened by Converso with `?session=<uuid>&token=<v1...>`. The
 *                token is a signed, two-minute claim about who this student is.
 *                It is exchanged once for the session, and from then on it is
 *                the only credential this app holds.
 *
 * There is no login here and there must never be one. This app has no database
 * key, no Supabase URL and no Clerk secret — it has a token that Converso minted
 * and Converso will check again on every call.
 *
 * This is the courtroom's session/launch.js with two deliberate differences,
 * both of them Next.js:
 *
 *   1. The query string is read lazily. The courtroom is a Vite SPA and can read
 *      `window.location` the moment its modules evaluate. The same line here
 *      also runs on the server during prerender, where there is no `window`.
 *   2. The Converso origin comes from `process.env.NEXT_PUBLIC_CONVERSO_URL`
 *      rather than `import.meta.env.VITE_CONVERSO_URL`. Same variable, same
 *      guarantee: it is fixed at build time and cannot be rewritten by whoever
 *      framed this page.
 *
 * What the room reports is counts, never sentences. The answers themselves are
 * generated by Ollama on the student's own machine and never leave it; that was
 * true of this app before the integration and staying out of the way of it is
 * the whole job here.
 */

import {
  LAUNCH_ERRORS,
  LAUNCH_ERROR_TEXT,
  SIMULATION_KIND,
} from "@converso/contracts";

/* --- where the query string came from ------------------------------------- */

/**
 * Read once, on the first call from a browser, and then remembered.
 *
 * Lazily because the server must not touch `window`; remembered because
 * `scrubUrl` takes the token out of the address bar a second later and a
 * re-read after that would find nothing.
 */
let launch = null;

function params() {
  if (launch) return launch;
  if (typeof window === "undefined") return { sessionId: "", token: "" };
  const query = new URLSearchParams(window.location.search);
  launch = {
    sessionId: query.get("session") || "",
    token: query.get("token") || "",
  };
  return launch;
}

/** True when Converso opened this page. False for `npm run dev`. */
export function isLaunched() {
  const { sessionId, token } = params();
  return Boolean(sessionId && token);
}

export function launchSessionId() {
  return params().sessionId;
}

/**
 * Which Converso to call back.
 *
 * An explicit build-time variable wins, and that ordering is the security of the
 * whole arrangement: if the origin were read out of the query string, a page
 * that framed this app could name its own server and be handed the student's
 * launch token. `NEXT_PUBLIC_CONVERSO_URL` is inlined at build time and cannot
 * be rewritten by whoever opened the iframe.
 *
 * The referrer is a fallback for the ordinary case where the two apps are served
 * from the same host in development and nobody has set anything. It is only
 * consulted when the variable is absent, and only its origin is used.
 */
let origin = null;

export function launchTarget() {
  if (origin !== null) return origin;

  const configured = process.env.NEXT_PUBLIC_CONVERSO_URL;
  if (configured) {
    origin = String(configured).replace(/\/+$/, "");
    return origin;
  }

  if (typeof document !== "undefined" && document.referrer) {
    try {
      origin = new URL(document.referrer).origin;
      return origin;
    } catch {
      /* not a URL; fall through */
    }
  }

  origin = typeof window === "undefined" ? "" : window.location.origin;
  return origin;
}

/* --- calling home --------------------------------------------------------- */

const authHeaders = () => ({
  // The routes accept this header, `x-launch-token`, or `?token=`. A header is
  // the right one for a fetch: it stays out of logs and out of the address bar.
  authorization: `Bearer ${params().token}`,
  "content-type": "application/json",
});

/**
 * Take the token out of the address bar.
 *
 * It has already been spent by the time this runs, so this is not what makes it
 * single-use — Converso's own `launch_jti` column does that. It is here because
 * a credential in a visible URL ends up in screenshots, in shared links and in
 * the back-forward history of a shared machine, and none of those are places it
 * needs to be.
 */
function scrubUrl() {
  try {
    const url = new URL(window.location.href);
    if (!url.searchParams.has("token")) return;
    url.searchParams.delete("token");
    window.history.replaceState({}, "", url.toString());
  } catch {
    /* a browser that dislikes replaceState is not worth failing a lesson over */
  }
}

const textFor = (code) =>
  LAUNCH_ERROR_TEXT[code] || LAUNCH_ERROR_TEXT[LAUNCH_ERRORS.UNAVAILABLE];

/**
 * Exchange the token for the session.
 *
 * Resolves to `{ ok: true, session, simulation }` or `{ ok: false, code, message }`.
 * It never throws and it never rejects: a classroom that cannot open should say
 * so on screen, not disappear behind an unhandled promise.
 */
export async function openLaunchSession() {
  if (!isLaunched()) {
    return {
      ok: false,
      code: LAUNCH_ERRORS.NO_TOKEN,
      message: textFor(LAUNCH_ERRORS.NO_TOKEN),
    };
  }

  const id = encodeURIComponent(params().sessionId);

  let res;
  try {
    res = await fetch(`${launchTarget()}/api/simulations/${id}`, {
      method: "GET",
      headers: authHeaders(),
      // No cookie is wanted or needed. The token is the whole credential, and
      // asking for credentials would require a CORS allow-credentials Converso
      // deliberately does not send.
      credentials: "omit",
      cache: "no-store",
    });
  } catch {
    return {
      ok: false,
      code: LAUNCH_ERRORS.UNAVAILABLE,
      message: "Could not reach Converso. Check the connection and open the lesson again.",
    };
  }

  const body = await res.json().catch(() => ({}));

  if (!res.ok) {
    const code =
      body.code || (res.status === 403 ? LAUNCH_ERRORS.WRONG_USER : LAUNCH_ERRORS.BAD_TOKEN);
    return { ok: false, code, message: body.error || textFor(code) };
  }

  scrubUrl();

  const { session, simulation } = body;
  if (simulation?.kind && simulation.kind !== SIMULATION_KIND.CLASSROOM) {
    // Converso minted a courtroom launch and it arrived here. Nothing about this
    // is the student's fault, so it is a configuration error stated plainly.
    return {
      ok: false,
      code: LAUNCH_ERRORS.UNAVAILABLE,
      message: `This session is a ${simulation.kind}, not a language lesson. Check which scene URL the lesson points at.`,
    };
  }

  return { ok: true, session, simulation };
}

/* --- reporting back ------------------------------------------------------- */

const post = async (url, payload, { beacon = false } = {}) => {
  const body = JSON.stringify(payload ?? {});

  // On unload there is no time for a fetch and no one left to read the answer.
  // A beacon cannot carry the Authorization header, so the token rides in the
  // query string for this one call — the same token the route already accepts
  // there, and the page is going away regardless.
  if (beacon && typeof navigator !== "undefined" && navigator.sendBeacon) {
    const sealed = `${url}${url.includes("?") ? "&" : "?"}token=${encodeURIComponent(params().token)}`;
    return navigator.sendBeacon(sealed, new Blob([body], { type: "application/json" }));
  }

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: authHeaders(),
      body,
      credentials: "omit",
    });
    return res.ok ? await res.json().catch(() => ({})) : null;
  } catch {
    return null;
  }
};

const sessionUrl = (path) =>
  `${launchTarget()}/api/simulations/${encodeURIComponent(params().sessionId)}${path}`;

const classroomUrl = () => `${launchTarget()}/api/classroom/session`;

/**
 * The room says which language and register it is in.
 *
 * Sent on arrival and again whenever the student changes either, because both
 * are pickers on the board and a lesson that started in Japanese and finished in
 * Korean is a Korean lesson. The route upserts, so re-announcing is cheap and
 * the last word wins.
 */
export function announceRoom({ language, register }) {
  if (!isLaunched()) return;
  void post(classroomUrl(), { language, register });
}

/**
 * One answer came back from the teacher.
 *
 * The model's *name* is recorded so an instructor can tell a 3B answer from a
 * 14B one. The question and the answer are not sent and never will be: they were
 * generated on the student's own machine and that is where they stay.
 */
export function noteExchange(model) {
  if (!isLaunched()) return;
  void post(classroomUrl(), { event: "exchange", model: model || null });
}

/**
 * A bookmark, not a grade.
 *
 * Converso stores this so a student who comes back sees where they were. It is
 * throttled because a lesson generates far more changes than anyone needs saved,
 * and it is fire-and-forget because a dropped bookmark costs a student nothing.
 */
let lastProgressAt = 0;
const PROGRESS_EVERY_MS = 15_000;

export function reportProgress(progress, { force = false } = {}) {
  if (!isLaunched()) return;
  const now = Date.now();
  if (!force && now - lastProgressAt < PROGRESS_EVERY_MS) return;
  lastProgressAt = now;
  void post(sessionUrl("/progress"), progress);
}

/**
 * The lesson is over.
 *
 * Sent once. Converso re-derives the score from these counts and ignores any
 * score sent with them, which is the right way round — this is a browser, and a
 * browser can be told to say anything. What it reports are tallies the store
 * kept as the lesson ran, and what comes back is what they were worth.
 */
let completed = false;

export async function reportComplete(result) {
  if (!isLaunched() || completed) return null;
  completed = true;
  return post(sessionUrl("/complete"), result);
}

/** The student closed the tab mid-lesson. Best effort by nature. */
export function reportAbandoned() {
  if (!isLaunched() || completed) return;
  post(sessionUrl("/abandon"), {}, { beacon: true });
}
